server {
    listen 80;
    listen [::]:80;
    server_name id.test.intdata.pro;

    access_log /var/log/nginx/id.test.intdata.pro.access.log main;
    error_log  /var/log/nginx/id.test.intdata.pro.error.log warn;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        root /var/www/id.test.intdata.pro;
        try_files $uri =404;
    }

    location / {
        return 308 https://id.dev.intdata.pro$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name id.test.intdata.pro;

    access_log /var/log/nginx/id.test.intdata.pro.access.log main;
    error_log  /var/log/nginx/id.test.intdata.pro.error.log warn;

    ssl_certificate     /etc/letsencrypt/live/id.test.intdata.pro/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/id.test.intdata.pro/privkey.pem;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    include /etc/nginx/snippets/ssl-params.conf;

    location / {
        return 308 https://id.dev.intdata.pro$request_uri;
    }
}
