[Unit]
StartLimitIntervalSec=10min
StartLimitBurst=5

[Service]
Restart=always
RestartSec=15
Environment=NODE_OPTIONS=--max-old-space-size=1024
MemoryAccounting=true
MemoryHigh=1200M
MemoryMax=1600M
MemorySwapMax=2048M
OOMScoreAdjust=500
TasksMax=256
