#!/usr/bin/env sh
set -eu
probe_bin="${PROBE_BIN:-/int/probe/client/probe}"
if [ -x "$probe_bin" ]; then
  exec "$probe_bin" coord "$@"
fi

probe_client_bin="${PROBE_CLIENT_BIN:-/int/probe/client/probe-client}"
if [ -x "$probe_client_bin" ]; then
  exec "$probe_client_bin" coord "$@"
fi

exec probe coord "$@"
