# Keycloak (prod SSO)

<VirtualHost *:8080>
    ServerName sso.intdata.pro

    ProxyPreserveHost On
    ProxyRequests Off
    RequestHeader set X-Forwarded-Proto "http"

    ProxyPass /.well-known/acme-challenge/ !
    Alias /.well-known/acme-challenge/ "/var/www/sso.intdata.pro/.well-known/acme-challenge/"

    ProxyPass        / http://127.0.0.1:28080/ retry=0 timeout=30
    ProxyPassReverse / http://127.0.0.1:28080/

    ErrorLog  /var/log/apache2/sso.intdata.pro-error.log
    CustomLog /var/log/apache2/sso.intdata.pro-access.log combined

    RewriteEngine On
    RewriteCond %{SERVER_NAME} =sso.intdata.pro
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
